[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -ra --html=reports/report.html --self-contained-html
markers =
    login: login-related tests
    search: product-search tests
